## Citibike Trips by Neighborhood,Borough, and CountyCode

Here we drop the unesscessary columns in the data

In [1]:
import pandas as pd 
import numpy as np

In [2]:
# read csv
trips= pd.read_csv('../../../tripneigh.csv')

In [3]:
trips.head()

,Unnamed: 0,Unnamed: 0.1,starttime,stoptime,start station name,end station name,usertype,birth year,gender,start_station_geoid,...,start_borough,start_county_code,start_station_neighborhood,index,Borough,end_county_code,end_borough_code,PUMA,Neighborhood Tabulation Area (NTA),end_station_neighborhood
0,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,...,Bronx,5.0,Claremont-Bathgate,58,Bronx,5.0,2.0,3708.0,BX14,East Concourse-Concourse Village
1,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,...,Bronx,5.0,Claremont-Bathgate,948,Brooklyn,47.0,3.0,4005.0,BK37,Park Slope-Gowanus
2,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,...,Bronx,5.0,Claremont-Bathgate,1288,Manhattan,61.0,1.0,3806.0,MN99,park-cemetery-etc-Manhattan
3,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,...,Bronx,5.0,Claremont-Bathgate,1406,Queens,81.0,4.0,4101.0,QN70,Astoria
4,1,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,...,Brooklyn,47.0,Park Slope-Gowanus,58,Bronx,5.0,2.0,3708.0,BX14,East Concourse-Concourse Village

In [5]:
# Dropping columns we're not going to use
trips = trips.drop(['Neighborhood Tabulation Area (NTA)','PUMA','Borough', 'index'], axis = 1)

In [6]:
trips.head()

,Unnamed: 0,Unnamed: 0.1,starttime,stoptime,start station name,end station name,usertype,birth year,gender,start_station_geoid,end_station_geoid,tripminutes,n_start_id,n_stop_id,start_borough,start_county_code,start_station_neighborhood,end_county_code,end_borough_code,end_station_neighborhood
0,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,3.606101e+10,11,16500.0,14300.0,Bronx,5.0,Claremont-Bathgate,5.0,2.0,East Concourse-Concourse Village
1,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,3.606101e+10,11,16500.0,14300.0,Bronx,5.0,Claremont-Bathgate,47.0,3.0,Park Slope-Gowanus
2,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,3.606101e+10,11,16500.0,14300.0,Bronx,5.0,Claremont-Bathgate,61.0,1.0,park-cemetery-etc-Manhattan
3,0,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,3.606101e+10,11,16500.0,14300.0,Bronx,5.0,Claremont-Bathgate,81.0,4.0,Astoria
4,1,0,2017-01-01 00:00:21,2017-01-01 00:11:41,W 82 St & Central Park West,Central Park West & W 72 St,Subscriber,1965.0,2,3.606102e+10,3.606101e+10,11,16500.0,14300.0,Brooklyn,47.0,Park Slope-Gowanus,5.0,2.0,East Concourse-Concourse Village

In [ ]:
trips.to_csv('./trip_neigh.csv')